"""Engram identity card export — portable Markdown summary for any AI tool.

Provided as ``IdentityCardMixin`` so the methods can be composed onto the
``Engram`` class at runtime via ``ReportsMixin``.
"""

from __future__ import annotations

import re

from .i18n import get_lang
from .storage import _now_iso

# Patterns that indicate config-file directives, not real lessons
_CONFIG_PATTERNS = re.compile(
    r"^\[(?:CLAUDE|AGENTS|README)\.md\]|"
    r"^\[.*\.md\]\s",
    re.IGNORECASE,
)

# XML/parameter tag remnants — cut everything from first tag onward
_XML_CUT = re.compile(
    r"</?(?:choice|parameter|reasoning)[^>]*>.*",
    re.DOTALL,
)

_MAX_CHOICE_LEN = 200

_MAX_DOMAINS = 15
_MAX_LESSONS = 10
_MAX_DECISIONS = 8


class IdentityCardMixin:
    """Export a portable Markdown identity card."""

    def export_identity_card(self) -> str:
        """Export a portable Markdown identity card.

        User can paste this into ANY AI tool (Claude, GPT, Cursor, etc.)
        and the AI will immediately understand their work style.
        Language follows user's profile.language preference (Chinese default).
        """
        zh = get_lang() == "zh"

        lines = [
            "# 我的 AI 协作身份卡" if zh else "# My AI Collaboration Identity Card",
            f"_生成时间: {_now_iso()}_" if zh else f"_Generated: {_now_iso()}_",
            "_由 Engram 自动生成_" if zh else "_Auto-generated by Engram_",
            "",
        ]

        profile = self.get_safe_profile()
        if profile:
            lines.append("## 我是谁" if zh else "## Who I Am")
            if profile.get("role"):
                lines.append(f"- {profile['role']}")
            if profile.get("description"):
                lines.append(f"- {profile['description']}")
            if profile.get("language"):
                lbl = "使用语言" if zh else "Language"
                lines.append(f"- {lbl}: {profile['language']}")
            if profile.get("technical_level"):
                lbl = "技术水平" if zh else "Technical level"
                lines.append(f"- {lbl}: {profile['technical_level']}")
            lines.append("")

        style = self.get_work_style()
        if style:
            lines.append("## 我的工作方式" if zh else "## How I Work")
            if style.get("preferences"):
                for k, v in style["preferences"].items():
                    lines.append(f"- {k}: {v}")
            if style.get("communication"):
                lines.append(f"- {style['communication']}")
            lines.append("")

        standards = self.get_quality_standards()
        if standards:
            lines.append("## 我的质量标准" if zh else "## My Quality Standards")
            if standards.get("rules"):
                for rule in standards["rules"]:
                    lines.append(f"- {rule}")
            lines.append("")

        domains = self.get_domains()
        if domains:
            lines.append("## 我的经验" if zh else "## My Experience")
            top_domains = sorted(
                domains.items(),
                key=lambda x: x[1].get("project_count", 0),
                reverse=True,
            )[:_MAX_DOMAINS]
            for name, info in top_domains:
                count = info.get("project_count", 0)
                unit = "个项目" if zh else "projects"
                lines.append(f"- {name} ({count} {unit})")
            remaining = len(domains) - len(top_domains)
            if remaining > 0:
                lbl = f"及其他 {remaining} 个领域" if zh else f"and {remaining} more domains"
                lines.append(f"- ...{lbl}")
            lines.append("")

        lessons = self.get_lessons(limit=30)
        if lessons:
            filtered = []
            for l in lessons:
                summary = l.get("summary", "")
                if not summary or _CONFIG_PATTERNS.match(summary):
                    continue
                filtered.append(summary)
                if len(filtered) >= _MAX_LESSONS:
                    break
            if filtered:
                lines.append(
                    "## 我踩过的坑（请帮我避免）" if zh
                    else "## Lessons Learned (Please Help Me Avoid)"
                )
                for s in filtered:
                    lines.append(f"- {s}")
                lines.append("")

        decisions = self.get_decisions(limit=_MAX_DECISIONS, _update_access=False)
        if decisions:
            lines.append(
                "## 我的关键决策（请遵循）" if zh
                else "## Key Decisions (Please Follow)"
            )
            for d in decisions:
                question = d.get("question") or d.get("title") or ""
                choice = d.get("choice", "")
                # Cut everything from first XML tag onward
                question = _XML_CUT.sub("", question).strip()
                choice = _XML_CUT.sub("", choice).strip()
                # Truncate overly long choices
                if len(choice) > _MAX_CHOICE_LEN:
                    choice = choice[:_MAX_CHOICE_LEN].rsplit(",", 1)[0] + "..."
                if not question and not choice:
                    continue
                if question and choice:
                    lines.append(f"- {question} → {choice}")
                elif question:
                    lines.append(f"- {question}")
                elif choice:
                    lines.append(f"- {choice}")
            lines.append("")

        lines.append("---")
        lines.append(
            "_把这段文字粘贴到任何 AI 对话的开头，AI 就能立刻了解你。_" if zh
            else "_Paste this at the start of any AI conversation so the AI instantly understands you._"
        )

        card = "\n".join(lines)

        # Also save to exports folder
        export_path = self._exports_dir / "identity_card.md"
        export_path.write_text(card, encoding="utf-8")

        return card
